### ISSUE TITLE
Installation fails for Python 3.10

### ISSUE THREAD

**Issue by quantumadventure** [madebr/pyOpt#64] opened 2023-08-10 11:15 UTC
Running ```python setup.py build_ext --inplace``` under Python 3.10 via pyenv I get some compilation errors, such as:

```
WARN: CCompilerOpt.dist_test[636] : CCompilerOpt._dist_test_spawn[770] : Command (gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/path/.pyenv/versions/3.10-dev/include/python3.10 -c /mounts/path/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/numpy/distutils/checks/cpu_avx512_spr.c -o /tmp/tmpyom63qb4/mounts/path/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/numpy/distutils/checks/cpu_avx512_spr.o -MMD -MF /tmp/tmpyom63qb4/mounts/path/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/numpy/distutils/checks/cpu_avx512_spr.o.d -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mno-mmx -mavx512cd -mavx512vl -mavx512bw -mavx512dq -mavx512vnni -mavx512ifma -mavx512vbmi -mavx512vbmi2 -mavx512bitalg -mavx512vpopcntdq -Werror) failed with exit status 1 output -> 
/mounts/path/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/numpy/distutils/checks/cpu_avx512_spr.c: In function ‘main’:
/mounts/path/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:22:5: error: unknown type name ‘__m512h’; did you mean ‘__m512bh’?
   22 |     __m512h a = _mm512_loadu_ph((void*)argv[argc-1]);
      |     ^~~~~~~
      |     __m512bh
/mounts/path/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:22:17: error: implicit declaration of function ‘_mm512_loadu_ph’; did you mean ‘_mm512_loadu_ps’? [-Werror=implicit-function-declaration]
   22 |     __m512h a = _mm512_loadu_ph((void*)argv[argc-1]);
      |                 ^~~~~~~~~~~~~~~
      |                 _mm512_loadu_ps
/mounts/path/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:23:5: error: unknown type name ‘__m512h’; did you mean ‘__m512bh’?
   23 |     __m512h temp = _mm512_fmadd_ph(a, a, a);
      |     ^~~~~~~
      |     __m512bh
/mounts/path/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:23:20: error: implicit declaration of function ‘_mm512_fmadd_ph’; did you mean ‘_mm512_fmadd_ps’? [-Werror=implicit-function-declaration]
   23 |     __m512h temp = _mm512_fmadd_ph(a, a, a);
      |                    ^~~~~~~~~~~~~~~
      |                    _mm512_fmadd_ps
/mounts/path/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:24:5: error: implicit declaration of function ‘_mm512_storeu_ph’; did you mean ‘_mm512_storeu_ps’? [-Werror=implicit-function-declaration]
   24 |     _mm512_storeu_ph((void*)(argv[argc-1]), temp);
      |     ^~~~~~~~~~~~~~~~
      |     _mm512_storeu_ps
cc1: all warnings being treated as errors

WARN: CCompilerOpt.feature_test[1575] : testing failed
```

Any ideas what I could do would be highly appreciated! Thanks

**Comment by madebr** [comment] 2023-08-10 14:53
I think the issue is not with pyopt (which is unmaintained, so please don't use this in new software).
Looks like you are building numpy from source for avx512 which your toolchain does not support.
I think you need to either install numpy first (`python -m pip install --user numpy`),
or [pass extra arguments to limit the cpu features numpy uses](https://numpy.org/doc/stable/reference/simd/build-options.html#i-am-building-numpy-for-my-local-use).

**Comment by quantumadventure** [comment] 2023-08-13 12:44
Thanks for the reply. I will try play with your suggestion and give a note in case of problems.

**Comment by alicebain** [comment] 2023-08-17 12:32
Hi all,

I have also some issues with the installation of pyOpt in Python 3.10. Some of the optimizers work, some don't. It would be really great, if somebody can find a solution to get all the optimizers running. It is quite crucial for a project and was the whole reason to use pyOpt.

This is what I tried.  I compiled them all one-by-one inplace via:

```
python setup.py build_ext --cpu-baseline="native" --inplace
```

The ones that I cannot import after building are: **ALGENCAN, FSQP, GCMMA, MMA, MMFD, NLPQL, NLPQLP, SNOPT**. These are the detailed errors that I get upon importing in Python:


For **ALGENCAN**:

```
Python 3.10.12+ (heads/3.10:917439d, Aug 16 2023, 18:31:40) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import algencan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: pyALGENCAN/algencan.cpython-310-x86_64-linux-gnu.so: undefined symbol: pyobj_from_character1
>>> 
```

For **FSQP**

```
Python 3.10.12+ (heads/3.10:917439d, Aug 16 2023, 18:31:40) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ffsqp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: pyFSQP/ffsqp.cpython-310-x86_64-linux-gnu.so: undefined symbol: ffsqp_

```

For **GCMMA**

```
Python 3.10.12+ (heads/3.10:917439d, Aug 16 2023, 18:31:40) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gcmma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: pyGCMMA/gcmma.cpython-310-x86_64-linux-gnu.so: undefined symbol: gcmma_
```

For **MMA**

```
Python 3.10.12+ (heads/3.10:917439d, Aug 16 2023, 18:31:40) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: pyMMA/mma.cpython-310-x86_64-linux-gnu.so: undefined symbol: mma_
```

For **MMFD**

```
Python 3.10.12+ (heads/3.10:917439d, Aug 16 2023, 18:31:40) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mmfd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: pyMMFD/mmfd.cpython-310-x86_64-linux-gnu.so: undefined symbol: ads_
```

For **NLPQL**

```
Python 3.10.12+ (heads/3.10:917439d, Aug 16 2023, 18:31:40) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nlpql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: pyNLPQL/nlpql.cpython-310-x86_64-linux-gnu.so: undefined symbol: nlpql1_
```

For **NLPQLP**

```
Python 3.10.12+ (heads/3.10:917439d, Aug 16 2023, 18:31:40) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nlpqlp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: pyNLPQLP/nlpqlp.cpython-310-x86_64-linux-gnu.so: undefined symbol: ql_
```

For **SNOPT** (throws also a lot of f2py errors while building):

```
Python 3.10.12+ (heads/3.10:917439d, Aug 16 2023, 18:31:40) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import snopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: pySNOPT/snopt.cpython-310-x86_64-linux-gnu.so: undefined symbol: sninit_
```

Thanks a lot for any help!

**Comment by madebr** [comment] 2023-08-23 00:00
The algencan error is not expected, and I have reported a reproducer upstream (=numpy).

About the other optimizers, these don't work because their fortran sources are missing.
You need to obtain a license for these, and add their sources in the appropriate locations.

**Comment by madebr** [comment] 2023-08-23 18:37
ALGENCAN links now without missing symbols, but it is 100% untested.

**Comment by madebr** [comment] 2023-08-23 18:37
Closing this issue, since there's nothing I can do about the other failing modules, apart from moving them to another location.

**Closed by madebr** 2023-08-23 18:37 UTC

**Comment by alicebain** [comment] 2023-08-24 07:59
Great, it compiles and importing `algencan` directly from `~/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/pyOpt/pyALGENCAN` does not show any errors anymore!

BUT there is still the problem that **ALGENCAN** and **FILTERSD** do not appear as methods to pyOpt like the others, e.g. COBYLA:

```
Python 3.10.12+ (heads/3.10:56e8c87, Aug 22 2023, 13:43:03) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyOpt
>>> pyOpt.
pyOpt.COBYLA(             pyOpt.Objective(          pyOpt.SOLVOPT(            pyOpt.pyFILTERSD          pyOpt.pyOpt_objective     pyOpt.pySLSQP
pyOpt.CONMIN(             pyOpt.Optimization(       pyOpt.Variable(           pyOpt.pyKSOPT             pyOpt.pyOpt_optimization  pyOpt.pySOLVOPT
pyOpt.Constraint(         pyOpt.Optimizer(          pyOpt.pyALGENCAN          pyOpt.pyMIDACO            pyOpt.pyOpt_optimizer     
pyOpt.Gradient(           pyOpt.PSQP(               pyOpt.pyALHSO             pyOpt.pyNSGA2             pyOpt.pyOpt_parameter     
pyOpt.History(            pyOpt.Parameter(          pyOpt.pyALPSO             pyOpt.pyOpt_constraint    pyOpt.pyOpt_variable      
pyOpt.KSOPT(              pyOpt.SDPEN(              pyOpt.pyCOBYLA            pyOpt.pyOpt_gradient      pyOpt.pyPSQP              
pyOpt.NSGA2(              pyOpt.SLSQP(              pyOpt.pyCONMIN            pyOpt.pyOpt_history       pyOpt.pySDPEN    
```

Therefore, using these solvers unfortunately does not work. Can you please have a look? This most likely requires only a minor change to the code as I am pretty sure that both worked in python2. Thanks a lot!

**Comment by madebr** [comment] 2023-08-24 09:07
I fixed algencan in 4e1aa7d0431f78c05377143a6eb4aee245d7004c.

`pyopt.FILTERSD` is apparently a wrapper around a python "filterSD" library, but Google doesn't tell me where I can find this library.
So unless you are able to track it down, consider filtersd dead too.

**Comment by alicebain** [comment] 2023-08-24 09:34
Thanks! The module is now there, but I get another error:

```
  File ".pyenv/versions/3.10-dev/lib/python3.10/site-packages/pyOpt/pyALGENCAN/pyALGENCAN.py", line 401, in __solve__
    algencan.algencan(epsfeas,epsopt,efacc,eoacc,iprint,ncomp,nn,xx,xl,xu,mm,lm,equatn,linear,coded,checkder,ff,cnormu,snorm,nlpsupn,inform,ifile,evalf,evalg,evalh,evalc,evaljac,evalhc,evalfc,evalgjac,evalgjacp,evalhl,evalhlp)
ValueError: algencan.algencan() 22nd argument (ifile) can't be converted to int
```

**Comment by madebr** [comment] 2023-08-24 16:22
I think I fixed the obvious python errors.
It looks like the algencan optimizer did not receive a lot of attention, or it has bit rotted a lot.
So I'm not sure it will even work, and it might hang.

> And about **FILTERSD** I found this: https://github.com/coin-or/filterSD

Cool. I looked at it again, and it was just a wrong import. It now imports.
But again, no guarantee on it working.

**Comment by alicebain** [comment] 2023-08-24 16:50
Both are working! Thanks so much for the effort!
